from __future__ import annotations

import hashlib
import time

import pyotp
import streamlit as st

from intraday_bot.config import settings
from intraday_bot.dhan_auth import _normalise_totp_secret


st.set_page_config(page_title="Dhan TOTP Diagnostic", layout="centered")

st.title("🔐 Dhan TOTP Diagnostic")
st.info(
    "This page checks only whether the TOTP generated from the configured Dhan setup secret "
    "matches the code currently shown by Aegis. It does NOT call Dhan, generate an Access Token, "
    "store the OTP, or display the TOTP secret."
)

secret = settings.dhan_totp_secret
if not secret:
    st.error("DHAN_TOTP_SECRET is not available in Streamlit Secrets.")
    st.stop()

try:
    normalised = _normalise_totp_secret(secret)
    generator = pyotp.TOTP(normalised)
    current_code = generator.now()
    interval = generator.interval
    digits = generator.digits
    algorithm = getattr(generator.digest, "__name__", "SHA1")
    remaining = int(generator.interval - (time.time() % generator.interval))
except Exception as exc:
    st.error(f"Unable to initialise TOTP locally: {exc}")
    st.stop()

fingerprint = hashlib.sha256(normalised.encode("utf-8")).hexdigest()[:12].upper()

st.subheader("Configured TOTP parameters")
col1, col2, col3, col4 = st.columns(4)
col1.metric("Digits", str(digits))
col2.metric("Period", f"{interval}s")
col3.metric("Algorithm", algorithm.upper())
col4.metric("Secret fingerprint", fingerprint)

st.caption(f"A fresh TOTP window begins in approximately {remaining} seconds.")

st.markdown("### Verify against Aegis")
code = st.text_input(
    "Enter the current 6-digit code shown by Aegis",
    max_chars=6,
    type="password",
    help="Enter it here only. Do not send the code in chat. The value is compared in memory and is not displayed or saved.",
)

if st.button("Check TOTP match", type="primary"):
    if not code.isdigit() or len(code) != 6:
        st.warning("Enter exactly 6 digits from the current Aegis code.")
    else:
        # Compare the user's current Aegis code to the code generated by
        # pyotp from the configured secret. Allow the adjacent windows to
        # avoid false negatives when the button is clicked at a 30-second edge.
        matched = any(
            pyotp.TOTP(normalised).at(int(time.time()) + offset) == code
            for offset in (-30, 0, 30)
        )
        if matched:
            st.success("✅ Aegis TOTP MATCHES the secret configured in Streamlit.")
            st.write("Python TOTP generation is consistent with Aegis. The next investigation should focus on Dhan's token-generation request rather than the secret itself.")
        else:
            st.error("❌ Aegis TOTP does NOT match the secret configured in Streamlit.")
            st.write("The Dhan setup secret stored in Streamlit is not producing the same code as Aegis. Do not change Dhan TOTP yet; verify that the exact Dhan setup secret used for the Aegis entry is the value stored in DHAN_TOTP_SECRET.")

st.divider()
st.caption("Security: the entered OTP is used only for an in-memory comparison; it is not written to the database, GitHub, logs, or session state.")
